export const BASE_SET_PRODUCTS: 'BASE_SET_PRODUCTS' = 'BASE_SET_PRODUCTS';
export const BASE_GET_PRODUCTS: 'BASE_GET_PRODUCTS' = 'BASE_GET_PRODUCTS';

export const BASE_CREATE_PRODUCT_REQUEST: 'BASE_CREATE_PRODUCT_REQUEST' =
  'BASE_CREATE_PRODUCT_REQUEST';
export const BASE_CREATE_PRODUCT_SUCCESS: 'BASE_CREATE_PRODUCT_SUCCESS' =
  'BASE_CREATE_PRODUCT_SUCCESS';
export const BASE_CREATE_PRODUCT_ERROR: 'BASE_CREATE_PRODUCT_ERROR' = 'BASE_CREATE_PRODUCT_ERROR';

export const BASE_DELETE_PRODUCT_REQUEST: 'BASE_DELETE_PRODUCT_REQUEST' =
  'BASE_DELETE_PRODUCT_REQUEST';
export const BASE_DELETE_PRODUCT_SUCCESS: 'BASE_DELETE_PRODUCT_SUCCESS' =
  'BASE_DELETE_PRODUCT_SUCCESS';
export const BASE_DELETE_PRODUCT_ERROR: 'BASE_DELETE_PRODUCT_ERROR' = 'BASE_DELETE_PRODUCT_ERROR';

export const BASE_APP_LOADING: 'BASE_APP_LOADING' = 'BASE_APP_LOADING';
