export const BASE_REGISTER_REQUEST: 'BASE_REGISTER_REQUEST' = 'BASE_REGISTER_REQUEST';
export const BASE_REGISTER_SUCCESS: 'BASE_REGISTER_SUCCESS' = 'BASE_REGISTER_SUCCESS';
export const BASE_REGISTER_ERROR: 'BASE_REGISTER_ERROR' = 'BASE_REGISTER_ERROR';
