export const BASE_LOGIN_REQUEST: 'BASE_LOGIN_REQUEST' = 'BASE_LOGIN_REQUEST';
export const BASE_LOGIN_SUCCESS: 'BASE_LOGIN_SUCCESS' = 'BASE_LOGIN_SUCCESS';
export const BASE_LOGIN_ERROR: 'BASE_LOGIN_ERROR' = 'BASE_LOGIN_ERROR';

export const BASE_AUTH_REQUEST: 'BASE_AUTH_REQUEST' = 'BASE_AUTH_REQUEST';
export const BASE_AUTH_SUCCESS: 'BASE_AUTH_SUCCESS' = 'BASE_AUTH_SUCCESS';
export const BASE_AUTH_ERROR: 'BASE_AUTH_ERROR' = 'BASE_AUTH_ERROR';

export const BASE_LOGOUT_REQUEST: 'BASE_LOGOUT_REQUEST' = 'BASE_LOGOUT_REQUEST';
